name: Continuous Delivery
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DevOpsTrab.zip
          path: |
            '**.py"
            README.me