name: Continuous Integration

push:
  branches:
  - main

jobs:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
        - name: Python Lint Code Scanning Action
          uses: advanced-security/python-lint-code-scanning-action@v1.1.1
          with:
            linter: pylint